# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    # Create missing simiulators
    sh(%q{
      if [ -z "`xcrun simctl list devices available | grep 'iPhone 8 Plus'`" ]; then
        xcrun simctl create 'iPhone 8 Plus' 'com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus';
      fi
      if [ -z "`xcrun simctl list devices available | grep 'iPhone 13 Pro Max'`" ]; then
        xcrun simctl create 'iPhone 13 Pro Max' 'com.apple.CoreSimulator.SimDeviceType.iPhone-13-Pro-Max';
      fi
      if [ -z "`xcrun simctl list devices available | grep 'iPhone 14 Pro Max'`" ]; then
        xcrun simctl create 'iPhone 14 Pro Max' 'com.apple.CoreSimulator.SimDeviceType.iPhone-14-Pro-Max';
      fi
      if [ -z "`xcrun simctl list devices available | grep 'iPad Pro (12.9-inch) (2nd generation)'`" ]; then
        xcrun simctl create 'iPad Pro (12.9-inch) (2nd generation)' 'com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-';
      fi
      if [ -z "`xcrun simctl list devices available | grep 'iPad Pro (12.9-inch) (6th generation)'`" ]; then
        xcrun simctl create 'iPad Pro (12.9-inch) (6th generation)' 'com.apple.CoreSimulator.SimDeviceType.iPad-Pro-12-9-inch-6th-generation-8GB';
      fi
    })
    capture_screenshots(scheme: "KDE ConnectUITests")
  end
end
